apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-db-19c
  namespace: public-service
  labels:
    app: oracle-db-19c
spec:
  serviceName: oracle-db-19c
  selector:
    matchLabels:
      app: oracle-db-19c
  template:
    metadata:
      labels:
        app: oracle-db-19c
    spec:
      containers:
      - image: oracle/database:19.3.0-ee
        name: oracle-db-19c
        ports:
        - containerPort: 1521
          name: oracle-db-19c-db
        - containerPort: 5500
          name: oracle-db-19c-oem
        env:
        - name: ORACLE_SID
          value: ORCLCDB
        - name: ORACLE_SID
          value: ORCLPDB1
        - name: ORACLE_PWD
          value: TOdo__9090
        volumeMounts:
        - name: data
          mountPath: /ORCL
      securityContext:
        runAsNonRoot: true
        runAsUser: 54321
        fsGroup: 54321
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oracle-db-pvc
