apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orcldb19c
  namespace: public-service
  labels:
    app: orcldb19c
spec:
  serviceName: orcldb19c
  selector:
    matchLabels:
      app: orcldb19c
  template:
    metadata:
      labels:
        app: orcldb19c
    spec:
      containers:
      - image: oracle/database:19.3.0-ee
        name: orcldb19c
        ports:
        - containerPort: 1521
          name: db
        - containerPort: 5500
          name: oem
        env:
        - name: ORACLE_SID
          value: CDB1
        - name: ORACLE_SID
          value: PDB1
        - name: ORACLE_PWD
          value: TOdo__9090
        volumeMounts:
        - name: data
          mountPath: /ORCL
      securityContext:
        runAsNonRoot: true
        runAsUser: 54321
        fsGroup: 54321
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oracle-db-pvc
