kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracle-db-data-pvc
  namespace: public-service
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracle-db-scripts-pvc
  namespace: public-service
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
