kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracle-db-pvc
  namespace: public-service
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
