apiVersion: v1
kind: Service
metadata:
 name: oracle-db-19c-svc
 namespace: public-service
spec:
 type: NodePort
 selector:
   app: orcldb19c
 ports:
   - name: db
     protocol: TCP
     port: 1521
     nodePort: 31521
   - name: oem
     protocol: TCP
     port: 5500
     nodePort: 31500
