apiVersion: v1
kind: Service
metadata:
 name: orcldb19c
 namespace: public-service
 labels:
   app: orcldb19c
spec:
 type: NodePort
 selector:
   app: orcldb19c
 ports:
   - name: db
     protocol: TCP
     port: 1521
     nodePort: 31521
   - name: oem
     protocol: TCP
     port: 5500
     nodePort: 31500
   - name: ords
     protocol: TCP
     port: 8080
     nodePort: 31580
